# Generated by Django 4.0.4 on 2022-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AustralianArmyWeapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weapon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='australian_army_weapons/')),
            ],
            options={
                'verbose_name_plural': 'Australian Army Weapons',
            },
        ),
    ]
