# Generated by Django 4.0.4 on 2022-05-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='createdat',
        ),
    ]
