# Generated by Django 4.0.4 on 2022-05-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_australianarmy_canadianarmy_irregularmilitia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiddleEasterAlliance',
            new_name='MiddleEasternAlliance',
        ),
    ]
