# Generated by Django 4.0.4 on 2022-05-16 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_australianarmy_rolename_alter_british_rolename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='australianarmy',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
