# Generated by Django 4.0.4 on 2022-05-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='body',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot_4_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sixth Equipment Slot #5 Amount'),
        ),
    ]
