# Generated by Django 4.0.4 on 2022-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_alerts_body_alter_australianarmy_sixthslot_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurgent',
            name='PrimaryMagazineRoundAmount',
        ),
        migrations.AddField(
            model_name='australianarmy',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='australianarmy',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='british',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='british',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='canadianarmy',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='canadianarmy',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='insurgent',
            name='PrimaryWeapon_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon #2'),
        ),
        migrations.AddField(
            model_name='insurgent',
            name='Primary_2_MagazineAmount',
            field=models.IntegerField(default=0, verbose_name='Role Primary Weapon Mag Amount #2'),
        ),
        migrations.AddField(
            model_name='insurgent',
            name='Primary_2_MagazineRoundAmount',
            field=models.IntegerField(default=0, verbose_name='Role Primary Weapon Mag Round Amount #2'),
        ),
        migrations.AddField(
            model_name='insurgent',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='insurgent',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='irregularmilitia',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='irregularmilitia',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='middleeasternalliance',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='middleeasternalliance',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='panasia',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='panasia',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='russiangroundforces',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='russiangroundforces',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='unitedstatesarmy',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='unitedstatesarmy',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AddField(
            model_name='unitedstatesmarinecore',
            name='thirdSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #4'),
        ),
        migrations.AddField(
            model_name='unitedstatesmarinecore',
            name='thirdSlot_3_Amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Third Equipment Slot #4 Amount'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='british',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='british',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='british',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='british',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='british',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='british',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='british',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='british',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='british',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='british',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='british',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='british',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, unique=True, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='Knife',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Knife'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='PrimaryFiringModes',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Firing Modes'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='PrimaryWeapon',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='PrimaryWeaponSights',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Role Primary Weapon Sight'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='fifthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='fifthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fifth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='fourthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='fourthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='fourthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Fourth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #3'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot_3',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #4'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='sixthSlot_4',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Sixth Equipment Slot #5'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='thirdSlot',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='thirdSlot_1',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #2'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='thirdSlot_2',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Third Equipment Slot #3'),
        ),
    ]
