# Generated by Django 4.0.4 on 2022-05-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_remove_insurgent_primarymagazineroundamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurgent',
            name='PrimaryMagazineRoundAmount',
            field=models.IntegerField(default=0, verbose_name='Role Primary Weapon Mag Round Amount'),
        ),
    ]
