# Generated by Django 4.0.4 on 2022-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_insurgent_primarymagazineroundamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurgent',
            name='hasPrimary2',
            field=models.BooleanField(default=False, help_text='Does the role have a second primary weapon?', verbose_name='Has Primary Weapon 2'),
        ),
    ]
