# Generated by Django 4.0.4 on 2022-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_australianarmy_isfiresupport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='australianarmy',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='british',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='canadianarmy',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='insurgent',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='irregularmilitia',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='middleeasternalliance',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='panasia',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='russiangroundforces',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='unitedstatesarmy',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AddField(
            model_name='unitedstatesmarinecore',
            name='isSquadRole',
            field=models.BooleanField(default=False, verbose_name='Is Regular Squad Role?'),
        ),
        migrations.AlterField(
            model_name='australianarmy',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='british',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='faction',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Role Faction'),
        ),
    ]
