# Generated by Django 4.0.4 on 2022-05-20 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_australianarmy_issquadrole_british_issquadrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australianarmy',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='british',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='canadianarmy',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='insurgent',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='irregularmilitia',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='middleeasternalliance',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='panasia',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdat',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='russiangroundforces',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='unitedstatesarmy',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
        migrations.AlterField(
            model_name='unitedstatesmarinecore',
            name='faction',
            field=models.CharField(default='N/A', max_length=35, verbose_name='Role Faction'),
        ),
    ]
