# Generated by Django 4.0.4 on 2022-05-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_australianarmy_faction_alter_british_faction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurgent',
            options={'verbose_name_plural': 'Insurgents'},
        ),
    ]
