# Generated by Django 4.0.4 on 2022-05-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_alter_alerts_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='createdat',
        ),
    ]
