# Generated by Django 4.0.4 on 2022-05-23 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_rename_createdat_post_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdateName', models.CharField(max_length=50, verbose_name='Changelog Name')),
                ('body', models.TextField(verbose_name='Changelog details')),
                ('createdat', models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Changelogs',
            },
        ),
    ]
